name: "gpt2"
backend: "python"
max_batch_size: 0

input [
  {
    name: "prompt"
    data_type: 13
    dims: [ 1 ]
  },
  {
    name: "max_new_tokens"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]

output [
  {
    name: "generated_text"
    data_type: 13
    dims: [ 1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
